### PR TITLE
Database

### PR DESCRIPTION
**Pull request by janrizmlibres**
Please accept asap

### CODE REVIEW

**Comment by clintgalendez** [comment]
i shall not accept this dumpfire

**Comment by janrizmlibres** [comment]
> i shall not accept this dumpfire

No! Why? Explain this please

**Comment by clintgalendez** [comment]
I shall not accept, for the time complexity is O(n! log n^2)

**Comment by janrizmlibres** [comment]
> I shall not accept, for the time complexity is O(n! log n^2)

This is blasphemy!

**Comment by clintgalendez** [comment]
Since you are the son of the CEO, fine, I will accept.

**Comment by janrizmlibres** [comment]
> Since you are the son of the CEO, fine, I will accept.

Noice. I will tell my dad to raise your salary

**Comment by clintgalendez** [comment]
Thank you, and goodbye you piece of shit

**Comment by janrizmlibres** [comment]
> Thank you, and goodbye you piece of shit

I revoke my statement

**Pull request merged**
